### ISSUE TITLE
allowClear does not show button when multiple = true

### ISSUE THREAD

**Issue by corrspt** [cibernox/ember-power-select#103]
Hi,

When I have a power-select with `multiple=true` and `allowClear=true` the little cross to remove the items is not shown. If I put `multiple=false` the cross appears correctly

**Comment by cibernox** [comment]
The `allowClear` option only works with single selects. I never thought about making it work with multiple selects since with them the usual thing to do is to remove only on element at a time (or use backspace).

I basically copied select2/selectize and they never provided that option, so I didn't either.

**Comment by corrspt** [comment]
I see, from the docs I didn't understand that. (Guess I should make a PR with that added, right :P?)

I guess that's a valid approach. I was thinking when you have several choices and wanted to remove them all, but I guess it's probably not that much of a requirement.

**Comment by cibernox** [comment]
If you could add a paragraph clarifying that this option only works for single selects that'd be great

**Comment by corrspt** [comment]
I might have some free time tonight, I'll try to help!

**Comment by corrspt** [comment]
I created #105 to help with documentation. I also included the information about allow clear in that PR
