### ISSUE TITLE
searchField required although searchEnabled=false

### ISSUE THREAD

**Issue by ktrhn** [cibernox/ember-power-select#1040]
> Assertion Failed: {{power-select}} If you want the default filtering to work on options that are not plain strings, you need to provide `searchField`"

With search disabled there should be no need to set the searchField?

I just noticed: It still "searches" and scrolls the list to a match even without the search input. I know this is also the default select UX but imho this is a little odd.

**Comment by raphaelns-developer** [comment]
Sorry for using a closed issue, but i'm still don't get it this behaviour. Why i still have to configure the `searchField` event if  the search input is disabled?

**Comment by Windvis** [comment]
It looks like this is intentional behaviour: https://github.com/cibernox/ember-power-select/pull/1029

**Comment by cibernox** [comment]
Sorry for missing this. The search field is mandatory even if you disable the searchbox, because the searchbox is not the only way to search in a select.
Like in native selects, when the select is closed and you press keys, it's going to select cycle through the values that start with that letter.

It's easier to see with an example. Go to https://ember-power-select.com/docs/the-search and in the **Disable the search box** section, focus the single select and press "L" and you'll see that "Lauren" gets selected.

The behavior is actually more complex than that even. If you had a select of all the countries sorted alphabetically and you type "U", "Uganda" would be selected. If you wait more than 200ms and type "U" again the selection will change to "Ukaine". If instead you would have typed "U" and then in less than 200ms "N", you have selected "United Arab Emirates". And if you wait for more than one second you the temporary search is reset and the next time you press a key will be considered a new search.

It seem subtle, but reproducing exactly the behavior of native selects is indeed full of subtleties.

**Comment by loxmys** [comment]
@cibernox Thanks

**Comment by rwwagner90** [comment]
@cibernox shouldn't this be documented and throw assertions then? Right now, if you think you are not doing any search and leave off these values, there is no assertion, but then if the user presses a key, you get an error and your app blows up.
