### ISSUE TITLE
Documentation out of date with regards to SASS

### ISSUE THREAD

**Issue by drakej** [cibernox/ember-power-select#1058]
I noticed that the installation documentation mentions adding the @import statement to the app.scss file if you're using SASS instead of vanilla CSS. The page being https://ember-power-select.com/docs/installation.

Here's the output when I installed the addon

`NPM: Installed ember-power-select
installing ember-power-select
Added import statement to app/styles/app.scss
Installed addon package.`

Version information:
_ember-cli: 2.14.2
node: 8.2.1
os: linux x64
npm: 5.3.0_

**Comment by cibernox** [comment]
Yeah, i tried to make the addon be as smart as possible and add the line for you, but this will only work if you install the addon by running `ember install ember-power-select`. If instead you just add it to your package.json and run `npm/yarn install` it won't get added because the addon's hooks won't run.

This is pretty common so I though it was still good to mention it. If the line is already there it's just a nice surprise.
