### ISSUE TITLE
Triggering the dropdown with another element

### ISSUE THREAD

**Issue by Macxim** [cibernox/ember-power-select#1066]
Hi,

Thank your for your work on this component 👍 

Sorry in advance if I'm missing something but is it possible to trigger `{{#power-select-multiple}}` on clicking of another element (different from the `input` tag)?

I want to trigger the dropdown on clicking on a button and I don't want the the selected option(s) to be in the input field. Just the button and the dropdown.

Maybe I'm looking at this the wrong way and I should style the input field so that it looks like a button? That sounds weird.

How can I achieve this?

Thank you for your time.

[See this twiddle](
https://ember-twiddle.com/ae69be48645be08a71b308eb0a7ddb6f?openFiles=templates.application.hbs%2C)

**Comment by cibernox** [comment]
If i've understood the UI you want to get, I think that the best option for what you want is to make the trigger be a button.

The trigger component can be replaced by literally ANYTHING you want passing `triggerComponent="my-custom-component"`.
Since the open/close behaviour is built-int, I think that just making your custom be a simple
`<button type="button">Hello</button>` will behave as you want.

**Comment by Macxim** [comment]
Oh alright. 
It seems I read too fast and I was passing an ID (the ID of the button) to `triggerComponent`.
My mistake. 

Thanks for replying so quickly!

**Comment by Macxim** [comment]
I successfully added a button as the trigger but now, obviously, the input field, which allows to search through the dropdown's items is gone.

Is it possible to display it anyway, let's say, inside, as the first item of the dropdown?

Do you understand?

https://ember-twiddle.com/ae69be48645be08a71b308eb0a7ddb6f?openFiles=templates.application.hbs%2C

**Comment by cibernox** [comment]
Yes, you can do anything you want really. In that case I would pass a `beforeOptionsComponent="my-select-searchbox"` with a template that is very similar to the one in the `beforeOptions` component used in single selects: https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/before-options.hbs

Don't be afraid because all the code, the main thing is that you need a text field that with `oninput={{onInput}}`.

**Comment by Macxim** [comment]
Thanks, this was really helpful!
That's a great component.

Thank you again for your time.
