### ISSUE TITLE
Version > 2.0.0 / Must setup rendering context

### ISSUE THREAD

**Issue by esbanarango** [cibernox/ember-power-select#1085]
Version > `2.0.0`

```js
import { selectChoose } from 'ember-power-select/test-support';
// ...
await selectSearch('[data-test-custom-field="Host"]', 'Carlos Doe');
// ...
```
![image 2018-04-08 at 12 04 43 am](https://user-images.githubusercontent.com/1156865/38463436-7898f5d2-3ac0-11e8-8dac-c6616ce50a41.png)

**Comment by esbanarango** [comment]
@cibernox We're on `"ember-cli-qunit": "^4.3.2"`. 🙏

**Comment by kevinansfield** [comment]
Hitting the same error using `clickTrigger` from `ember-basic-dropdown`. We're using `ember-cli-mocha` rather than `ember-cli-qunit`

```
Error: Must setup rendering context before attempting to interact with elements.
    at getRootElement (assets/test-support-3b6f7d369d74366c350475c8ccf8f11f.js:52931:13)
    at getElement (assets/test-support-3b6f7d369d74366c350475c8ccf8f11f.js:52315:53)
    at then (assets/test-support-3b6f7d369d74366c350475c8ccf8f11f.js:52544:45)
    at tryCatcher (assets/vendor-cbe91fb5da5a795c2b5bc5d74a6cc3fc.js:75156:21)
    at invokeCallback (assets/vendor-cbe91fb5da5a795c2b5bc5d74a6cc3fc.js:75328:33)
    at publish (assets/vendor-cbe91fb5da5a795c2b5bc5d74a6cc3fc.js:75314:9)
    at Ember.run.backburner.schedule (assets/test-support-3b6f7d369d74366c350475c8ccf8f11f.js:56788:9)
    at invoke (assets/vendor-cbe91fb5da5a795c2b5bc5d74a6cc3fc.js:33666:24)
    at Queue.flush (assets/vendor-cbe91fb5da5a795c2b5bc5d74a6cc3fc.js:33586:25)
    at DeferredActionQueues.flush (assets/vendor-cbe91fb5da5a795c2b5bc5d74a6cc3fc.js:33739:31)
```

**Comment by nfc036** [comment]
Any progress here? Due to this problem we are forced to still use ember-power-select version 1.10.4 as the latest working version. When updating to any version >= 2.0.0 our tests are failing with "Must setup rendering context before attempting to interact with elements." All other npm packages used are at their latest version. (i.e. ember-cli-qunit@4.3.2)

**Comment by andrewzamojc-pd** [comment]
I might have a hint. Something something lazy loading. When running my broken test locally in Chrome, if I put a `debugger;` just before `await selectSearch('.ember-power-select-trigger', 'blah')` I can inspect the DOM. I notice that the `'.ember-power-select-trigger'` div has spans inside of it instead of inputs. Looking at the selectSearch function, it does have some selectors for `input[type=search]` which might not be present yet. https://github.com/cibernox/ember-power-select/blob/c2f3bc183c00173be7d8bec53cfda18d6a0f11ff/addon-test-support/index.js#L59

**Comment by andrewzamojc-pd** [comment]
This person got the same error, and the link has some info about lazy loading, but the suggested helper sends me down a maze of errors. https://github.com/emberjs/ember-test-helpers/issues/281

**Comment by danwenzel** [comment]
It turns out in our case, we were using the old style of acceptance tests, without using `moduleForAcceptance`.  Instead, we had a manual `start-app.js` file that wasn't setting up the test context.  If you're in the same boat:

Add the following to start-app.js:

```js
import { setContext } from 'ember-test-helpers';
...
// inside the function:
QUnit.config.current.testEnvironment.owner = application.__deprecatedInstance__;
setContext(QUnit.config.current.testEnvironment);
```

and then to destroy-app.js:

```js
import { unsetContext } from 'ember-test-helpers';
...
// inside the function:
unsetContext();
```

(thanks @rwjblue for that solution!)


We also had the same issue with some component integration tests.  The only solution I could come up with there was to upgrade to the new testing API for those files.  It actually wasn't too painful, thanks to https://github.com/rwjblue/ember-qunit-codemod and https://github.com/simonihmig/ember-test-helpers-codemod

**Comment by esbanarango** [comment]
@danwenzel Thank you for sharing this! I'll try it! 🙏

**Comment by bmaehr** [comment]
We have already the new style of acceptance tests but still the problem with selectSearch.

Additionally adding the changes from @danwenzel did not really help.

**Comment by nfc036** [comment]
I can confirm that in my project switching to the new style acceptance tests (using setupApplicationTest) resolves the "must setup rendering context"-issue.

**Comment by bmaehr** [comment]
setupApplicationTest was the keyword to fix our acceptance tests. 
Thank you to @nfc036

**Comment by bmaehr** [comment]
I was able to get the new style of tests working configuring it like described in https://github.com/emberjs/ember-qunit/issues/309
Nevertheless there are still problems because andThen is not workung and other errors are occuring.
