### ISSUE TITLE
Remove Option passing to function

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-power-select#110]
Awesome component btw.  Amazing how far this has come in a short amount of time.  

(https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/multiple.js#L82)

Is there any future plans to open up an api to allow the specific removed option to be passed to a `removal` function?  In our case, we have a lot of specific logic that needs to be applied to this removed option.  It seems our only choice right now for an onchange action is to compare the newSelection to what currently exists in our application and then applying that specific logic to the derived missing objects (those objects that don't exist in the newSelection vs. what exists locally).

Is this type of feature something you would be open for a pull request?

**Comment by corrspt** [comment]
I've actually encountered the same issue but up until now, my situations didn't demand a specific `removeOption` and I could just use the `onchange`
I was hesitant on suggesting this because it would be a breaking change on the component (for people having done the logic for removal in the onchange function), but I can easily see myself needing this in the future, so I'll make a :1 on this as well :)

**Comment by cibernox** [comment]
I considered that initially but at the end I decided to keep the api of the component minimal with only a `onchange` action triggered both for additions and removals, and let the users diff the new and old values  themselves.

What I want to advocate with this component is the community to build more purpose-specific addons on top and perhaps publish them. Also, if eventually any of those addons happens to be acknowledged as extremely useful and a better solution, fusion it into the core of this one.

My suggestion instead of a PR is to build a meta-addon that could be called `power-select-differ` or something alike with an API like this one:

```hbs
{{#power-select-differ options=people selected=politicians onAdd=(action "corrupt") onRemove=(action "inprison")  as |user|}}
  {{user.name}}
{{/power-select-differ}}
```

And within that component you diff the collections and call any of those actions depending on what happened:

```js
actions: {
  didChange(newSelection) {
    let oldSelection = this.get('people');
    let { removals, additions } = diffCollection(oldSelection, newSelection);
    if (removals.length > 0) {
       this.get('onRemove')(removals);
    }
    if (additions.length > 0) {
      this.get('onAdd')(additions);
    }
  }
}
```

That way the API can be refined separately from the core component. 

An example of this is https://github.com/cibernox/ember-power-select-blockless, that exposes a simplified form of this addon for very simple usages. 

If you do so, I'll add it to the list of addons: http://www.ember-power-select.com/addons

Make sense?

**Comment by snewcomer** [comment]
Great!  Sounds like I have some work to do!
