### ISSUE TITLE
Custom Status Icon

### ISSUE THREAD

**Issue by erichonkanen** [cibernox/ember-power-select#1174]
I use fontawesome 5 and I'd like to use a custom svg icon for the select dropdown icon, is this supported?

**Comment by cibernox** [comment]
Yes, but is a bit involved.

All sub components of the select (See [this section](https://ember-power-select.com/docs/architecture) for a detail of the subcomponents that select is comprised from) can be swapped by your own, so you can do pretty much anything you want.

You need to do
```hbs
{{#power-select selected=selected options=options triggerComponent="my-custom-trigger" as |item| }}
  {{item}}
{{/power-select}}
```

Your `my-custom-trigger` component can just be

```hbs
import TriggerComponent from 'ember-power-select/components/power-select/trigger';
export TriggerComponent.extend();
```

And your template can be a copy if [the default template](https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/trigger.hbs) modified to render an svg icon instead of `<span class="ember-power-select-status-icon"></span>`.

Using this technique of replacing components you can customize the select without limits.

**Comment by erichonkanen** [comment]
thanks @cibernox :)
