### ISSUE TITLE
Default functionality not Working 

### ISSUE THREAD

**Issue by teakap** [cibernox/ember-power-select#1200]
I am running in several issues, that I don't believe are caused by the addon but I don't know how to resolve them. 

As soon as I install and use the addon I run into exactly [this issue](https://github.com/cibernox/ember-power-select/issues/1187) which I hacked with catching the onfocus event and then opening the dropdown. Afterwards the dropdown doesn't close when I select an option (probably cause it's triggering again the onfocus event). I can continue finding hacky solutions but it doesn't make any sense since for most of people this works out of the box. 

Does anyone have a clue where this could be coming from ? 

Thanks in advance!

**Comment by teakap** [comment]
@cibernox I can't provide some reproduction cause on a clean project it's working properly. Haven't found any overlapping divs though yet. Will have a look at it again the next days and update this if I find anything. Nevertheless it's not an issue from the addon, so I am closing this.

Thanks you for the immediate feedback!

**Comment by harmvandeven** [comment]
@cibernox and @teakap, I believe I've nailed done the issue. It seems to be related to the `ember-power-select addon`, at least for me it does. I've had the exact same experience as @teakap and @ivanhueso (in #1187). 

For me, the issue arises when I'm using a custom `index.php` file to inject my ember, not the standard `index.html`. Somehow in the `ember s` `dist` version of the `index.html` there one line added `<div id="ember-basic-dropdown-wormhole"></div>`. Once I added that to my `index.php` all issues where gone. Probably it is added to `{{content-for "body-footer"}}` but anything rarely is (in my experience at least).

Either this is the most logical place, and I'm just pointing other people with the same experience in the right direction, or the adding of the `<div id="ember-basic-dropdown-wormhole"></div>` line could be done on initialisation instead of building?

**Comment by cibernox** [comment]
@harmvandeven Having the app rendered in an unconventional spot indeed requires you to add the `<div id="ember-basic-dropdown-wormhole">` yourself. It is mentioned in the docs in a couple places, and specifically in https://ember-power-select.com/docs/troubleshooting

**Comment by harmvandeven** [comment]
thanks @cibernox for the quick reply! I was stupid enough to not read the _troubleshooting_ section, but to just interpret it as a weird bug, my apologies. If anyone reads this... look at the troubleshooting section :) [https://ember-power-select.com/docs/troubleshooting](url)

**Comment by cibernox** [comment]
@harmvandeven this has bitten a few people before. Perhaps we could add some sort of development assertion that outputs a helpful error message.

**Comment by cibernox** [comment]
@harmvandeven I did this: I hope that this assertion message prevents nobody else to loose time tracking such a simple thing to check. 

Sorry for the inconvenience.
