### ISSUE TITLE
Uncaught Error: Could not find module ember-compatibility-helpers imported from ember-concurrency/-task-property

### ISSUE THREAD

**Issue by AleksandrBorovkov** [cibernox/ember-power-select#1232]
I've got
`Uncaught Error: Could not find module ember-compatibility-helpers imported from ember-concurrency/-task-property`
after upgrade from 2.3.1 to 2.3.3 version

**Comment by ef4** [comment]
I found the source of this bug. 

ember-power-select uses ember-concurrency which uses ember-compatibility-helpers. ember-compatibility-helpers has an `included` hook that installs its babel transform.

Only the first copy of of `ember-power-select` that runs calls `this._super.included.apply(this, arguments);`. This means all the other copies will depend on a broken ember-concurrency.

Sometimes this bug hides because of the way the multiple copies of ember-concurrency get combined into one. Sometimes it probably hides because of ember-cli tree caching that causes only the first one built to actually run. But depending on how your dependency graph falls out, you can end up with the broken copy in your app.

**Comment by cibernox** [comment]
@eaf4 I'm semewhat confused. What can EPS do to fix this?

**Comment by danwenzel** [comment]
Thank you @ef4 !  This bug has been driving me bananas...

@cibernox - Any chance this could be release as patch versions to 2.x minors?  It looks like 3.x has some breaking changes, and I'm sure lots of folks aren't quite ready for that but will still need to fix this issue.

**Comment by cibernox** [comment]
@danwenzel I just did with 2.3.5

**Comment by danwenzel** [comment]
Awesome, thank you!

**Comment by lifeart** [comment]
getting same issue with eps 4.1.0
![image](https://user-images.githubusercontent.com/1360552/99904656-47448700-2cdd-11eb-9d51-c6b7403e8fdf.png)

**Comment by danwenzel** [comment]
@lifeart - The latest ember-power-select-infinity declares `ember-power-select@^2.0.1`.  The fix for this issue is `2.3.5`, which is in range of that.  You should be able to upgrade to get it to work.
