### ISSUE TITLE
[Documentation] What is the purpose of `this` in templates?

### ISSUE THREAD

**Issue by Redsandro** [cibernox/ember-power-select#1347]
In the documentation, I see a lot of `this` prepended to controller properties.

For example:

```
<PowerSelect @options={{this.names}} @onChange={{this.foo}} as |name|>
    {{name}}
</PowerSelect>
```

What is the purpose of `this`? Trial and error showed me that it works both with and without. It confuses me, as until now, most components I've used don't use `this` in their template documentation. I prefer not to use a different style of referencing properties for this components compared to the other ones in my app. However, I also prefer to follow the documentation as closely as possible.

It would help if I understand the logic of using `this` and the benefits of doing so.

---

**Full disclosure:** I am assuming it is (1) for reading clarity by distinguishing between scopes and (2) for allowing to use the same variable name in different scopes without overriding the parent one. I'm assuming it is perfectly fine to forego using `this` in your template if you prefer less verbosity for reasons, for example visual impairment.

However, that's just an assumption. I haven't seen this before and I like to know for sure.

**Comment by cibernox** [comment]
It is now considered a good practice to use `this.foo` instead of `foo` when accessing a property in the current context (a component or a controller) to help the reader understand where a value is coming from. In fact the last version ember-template-lint has a rule to enforce it.

The idea is that following some conventions it makes easier to anyone reading some template to know from where the values referenced in it come from.

Example component:
```hbs
{{#each this.users as |user|}}
  <button {{on "click" @selectUser}}>{{user}}</button>
{{/each}}
```

In here, `this.users` is a property (a getter or a computed property in the current context). `@selectUser` is an argument passed in to this component from the outside and `user`, since it doesn't have a `@` or `this.` before means it's an argument yielded from some block somewhere in the same template.

It's a very simple convention that IMO improves readability and minimizes looking around where a value comes from. I'd recommend using the last version ember-cli-template-lint that includes this rule, as it's very easy to make mistakes following it.

**Comment by Redsandro** [comment]
@cibernox thank you for the clear explanation. 

I still use a lot of old `{{#` helpers. Perhaps it's time for me to find a good guide and learn about all the non-trivial differences Ember has made in the last 10 versions so I can use up-to-date tooling and linting.

**Comment by cah-briangantzler** [comment]
Im pretty sure for glimmer components its mandatory. So yea, you should definitely use this and @ in the template where appropriate

**Comment by cibernox** [comment]
Indeed `@` is mandatory, but the distinction between `this.foo` and `foo` is just conventional for now. That's why having ember-template-lint enforcing it is so important, otherwise it's almost impossible to be totally consistent.

I believe that the final goal is at some point in the middle-term future disallow `foo` for accessing properties in the current context, and that should make the resolver faster.
