### ISSUE TITLE
`search` shows previous results while loading

### ISSUE THREAD

**Issue by mydea** [cibernox/ember-power-select#1403]
I am not 100% sure if that was always the case, but I seem to remember the behavior used to be different. 

When you use a custom `search` method that returns a promise, the behavior is a bit weird IMHO: 

* You type into the search bar. it shows "loading", once the promise resolves it shows the returned results to select from.
* If I now type something else, it shows "loading" again but also shows the previously loaded records below? Even if they do not match the search at all.

You can try it here: https://ember-power-select.com/docs/custom-search-action for example, type `a`, wait for the results, than delete it and type `z`, and it will show the "a" results while loading the ones for "z".

It would make more sense to revert to the initial `loading` state in that case, I would say, as the shown results simply do not match my new search.

**Comment by cibernox** [comment]
This behavior has been like that for years. It's intentional. 

One reason is that very often, search happens as you type (you go from "new y" to "new yo" and then to "new yor" and finally to "new york"). In that very common situation often the top results do continue to match and stay in place, and keeping them is more efficient and causes less visual churn. 
The second reason is also visual churn, as removing and re-rendering results with every new letter causes the box to go from X number to results results to 1 (the loading message) then to Y results then back to 1 then to the final Z results. This expand and collapse of the list of results is rather unpleasant.

Of course if you disagree with this you can override by passing your own `@optionsComponent`, which can be [a copy of the original one](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/options.hbs) that only renders the results if `@select.loading` is false.
