### ISSUE TITLE
Passing actual components into params.

### ISSUE THREAD

**Issue by ErvinSabic** [cibernox/ember-power-select#1428]
Here is a feature addition I wrote up in a fork that I think the core could benefit from. The ability to pass actual components into params that are component related such as `@noMatchesMessageComponent`. I think this is useful because I can pass params to the components that I give Power Select. 

https://github.com/ErvinSabic/ember-power-select

If you download and run this you can see where I created an example in the dummy app. I did however only create an implementation for `@noMatchesMessageComponent` because that's where I personally needed it. I think that this could be used everywhere for component related params passed to Power Select. 

Looks something like this 
```
<PowerSelect
    @selected={{this.destination}}
    @options={{this.cities}}
    @onChange={{this.chooseDestination}}
    @searchEnabled=true
    @noMatchesMessageComponent={{ component 'no-items' thing="your destination"}}
    as |name|
>
  {{name}}
</PowerSelect>
```

**Comment by cah-briangantzler** [comment]
Several params already represent components, such as beforeOptionsComponent and afterOptionsComponent. Im surprised that when you altered the fork you didnt see that this was implemented about 3 months ago. It is documentd here https://ember-power-select.com/docs/api-reference (look for noMatchesMessageComponent, used same name).   The code for it is here https://github.com/cibernox/ember-power-select/blame/master/addon/components/power-select.hbs#L93


Ahh, it is present in your code at https://github.com/ErvinSabic/ember-power-select/blob/master/addon/components/power-select.hbs#L96 using the same variable. The if you did is not needed. If you revert your code, you should find it still works as is since you used the same name.

**Comment by ErvinSabic** [comment]
> Several params already represent components, such as beforeOptionsComponent and afterOptionsComponent. Im surprised that when you altered the fork you didnt see that this was implemented about 3 months ago. It is documentd here https://ember-power-select.com/docs/api-reference (look for noMatchesMessageComponent, used same name). The code for it is here https://github.com/cibernox/ember-power-select/blame/master/addon/components/power-select.hbs#L93
> 
> Ahh, it is present in your code at https://github.com/ErvinSabic/ember-power-select/blob/master/addon/components/power-select.hbs#L96 using the same variable. The if you did is not needed. If you revert your code, you should find it still works as is since you used the same name.

Ya know, I did this initially and for whatever reason my params were just not getting passed with my component. The way I'm reading that code is place the component that is defined in the string (according to API) `@noMatchesComponent` OR use our default `power-select/no-matches-message`. It works now but the way I read the code initially was that it was going to just take whatever I passed in as a string and pretty much ignore my other params that I would try to pass in with my component.. Making for a very boring component. 

The 3 month timeline is enough for me to have not updated the library to latest on my end so I just didn't have the feature and figured I'd write it and that the solution that was already there when I forked just wasn't working haha. 

Thanks for letting me know, I'll go ahead and close the issue! My mistake!
