### ISSUE TITLE
using get helper with selected property?

### ISSUE THREAD

**Issue by jcope2013** [cibernox/ember-power-select#146]
```
{{#each model.rawPayerNamesArray as |payerName|}}
{{#power-select search=(action "queryPayers") selected=(get model payerName) onchange=(action "setPayerName" payerName) as |payer|}}
	{{payer.payerName}}
{{/power-select}}
{{/each}}
```

so the onchange action sets the dynamic payerName key on the model with the value selected in the dropdown, using ``` {{get model payerName}} ```in the template confirms that indeed the value is getting set properly for this dynamic payerName key but when I bind to the selected to the get helper the dropdown stays empty, the only way for it to be properly selected is to hardcode the model.x (payerName) property next to the selected binding but then that limits me from dynamically using it with the get helper and limits me to one value only

so is the get helper supported or is this a known limitation?

I am on ember 1.13.11 and power select 0.5.2 and ember-get-helper 1.0.4

**Comment by cibernox** [comment]
I have to admit that I'm a bit lost in the example & explanation, but as you formulates seems to me like a problem with the get helper.

Can you paste your `setPayerName` actions to see if I make a better idea of what is going on?

**Comment by jcope2013** [comment]
``` 
actions: {
    setPayerName(payerName, value) {
      this.get('model').set(payerName, value.get('id'));
    }
```

``` {{ get model payerName }} ``` in my template will print out the selected value id to the screen

binding to say ``` selected=model.blue_shield ``` with payerName being blue_shield will work in the power select but when binding using the get syntax with the payerName of blue_shield it doesnt bind correctly

**Comment by cibernox** [comment]
This component takes the value and operates with it. If the value is not updated seems unrelated to the component.

That said, there is something that confuses me. The return value of `queryPayers` is a list of users (payers)? I ask that because `selected=(get model payerName)` (that makes me think that the selected value is a string) while in the block passed to the component  you do `{{payer.payerName}}`, which makes me think that the values must be objects of some kind. 
Remember that the given block will apply to each options options and the selected value, so they both should be of the same kind

I am relatively familiar with the code of the get helper, so if you can create a minimum reproducible example that I can download I feel confident that I'll be able to fix it.

**Comment by jcope2013** [comment]
@cibernox thanks that did it, i was setting the value as an id (string) not the full object and hoping it would automatically map to the correct item in the dropdown using the id
