### ISSUE TITLE
Style issue between firefox and chrome

### ISSUE THREAD

**Issue by oliverlj** [cibernox/ember-power-select#1464]
Firefox :
![image](https://user-images.githubusercontent.com/1826498/132520686-c9efd73a-b5da-426d-86f9-6b22290b7e7b.png)

Chrome :
![image](https://user-images.githubusercontent.com/1826498/132520804-1abdfc36-951f-4b82-a875-fd4005972725.png)

```hbs
 <div class="font-weight-bold">{{t "components.saving.fixed-rate.parameters.monthly"}}</div>
                <form.element
                  data-test-transfer-type
                  @controlType="power-select"
                  @value={{this.parameters.transferType}}
                  @onChange={{this.setTransferType}}
                  @options={{this.transferTypes}}
                  class="font-weight-bold mb-1 px-1"
                  as |el|
                >
                  <el.control @matchTriggerWidth={{false}} as |transfer-type|>
                    {{t (concat "enums.transfer-type." transfer-type)}}
                  </el.control>
                </form.element>
```

**Comment by cibernox** [comment]
I'm not sure what's going on there, but I can only assume the bug is not in ember-power-select but on whatever form-builder library is wrapping it to make it. For what I can see there's no such difference in styles in https://ember-power-select.com

I'm closing this, but feel free to reopen if you can share more specifics that help track that down. At first glance seems that the form builder is styling the component like if it was an `<input type="number">`

**Comment by oliverlj** [comment]
Thanks to you had a look. cannot reproduce with ember-twiddle. just a style issue beween admin-lte and bootstrap. I will have a look

**Comment by oliverlj** [comment]
I've added a "scrollbar-width: none;" to fix my issue
