### ISSUE TITLE
options list does not render when in a modal

### ISSUE THREAD

**Issue by gkaran** [cibernox/ember-power-select#149]
I'm using a power-select in a boostrap modal and when I click on the select the options list does not render.

From what I found this is due to the fact that `.modal` has a `z-index` of 1050 whereas the `.ember-power-select-dropdown` has none and thus rendering behind the modal.

So simply setting a `z-index` would be sufficient.

**Comment by cibernox** [comment]
I am aware of that. In bootstrap dropdowns (like ember-power-select) have a z-index of 1000 and modals have a z-index of 1050, so modals are on top. This component copied those values.

https://github.com/twbs/bootstrap/blob/e38f066d8c203c3e032da0ff23cd2d6098ee2dd6/less/variables.less#L272-L278

This is by design. If a modal opens unexpectedly while you have a dropdown opened you don't want the list of the dropdown to be on top. This situation is unpredictable, so this is the safest default.

When the select component is inside a modal you can anticipate that and:

a) Design for it, add a specific class (`class="in-modal"`) to the select (that will make the dropdown have also a special class derived from the one you passed) and customize it's z-index so it's above the modal.
b) Pass `renderInPlace=true` to not render the modal in the root of the body but inside the modal, so it's not affected by the z-index.

I hope it helps
