### ISSUE TITLE
If power-select is render in a scrollable element, it won't trigger reposition when scroll

### ISSUE THREAD

**Issue by rayjcwu** [cibernox/ember-power-select#168]
from basic-dropdown code, it only monitor window's scroll event.
If you put power-select in another element with scrollbar, while scrolling, dropdown won't move at all.

**Comment by miguelcobain** [comment]
Good catch.

**Comment by cibernox** [comment]
Yes, I was aware of that. That is one of the reasons why the component accepts a `renderInPlace=true` option to not be attached to the body but rendered in place.

The problem is not track the scroll event of a different element, the problem is detecting when an the trigger exits the viewport. 

Example of what can go wrong: http://quick.as/wxjki3oo0

There is a couple new APIs in the browser for that, but they are not widely supported yet. Perhaps they can be polyfilled, but I haven't checked it.

Indeed that would be nice addition, but since `renderInPlace=true` will probably be good enough for most use cases it's just not very high in my list of TODOs.

**Comment by rayjcwu** [comment]
Oh yeah, `renderInPlace=true` solve the scrolling problem, thank you.

However, when I use it, the element with `.ember-power-select-dropdown` lost `style="width: ..."`, therefore dropdown size will change depends on the content. I think that's handle by `ember-wormhole`, let me dig in...

**Comment by rayjcwu** [comment]
So the problem in `ember-power-select: 0.5.2` is when using `renderInPlace=true`, it will exit repositionDropdown in first line, therefore it won't go to  `matchTriggerWidth` line.

**Comment by cibernox** [comment]
Talking from memory, because 0.5.2 has some time, I'd say that is intended. The list of options should have display block and therefore take all the width of the container.
