### ISSUE TITLE
Issue when using multiple=true and pressing backspace while the caret is next to a selected item

### ISSUE THREAD

**Issue by rhyek** [cibernox/ember-power-select#173]
Currently the selected item is removed from the list, which is great, but the complete text is left on the input and you need to either manually delete it all or press `Escape`. It would be great if on the initial backspace it removed the item as well as its text.

This behavior is also seen at http://www.ember-power-select.com/docs/multiple-selection.

**Comment by cibernox** [comment]
This is on purpose. I copied this behaviour from select2: https://select2.github.io/examples.html

You probably can customize this by passing a custom `selectedComponent` that handles the `onkeydown` event in a different way.

Let me know if you need some guidance.

**Comment by cibernox** [comment]
Released on 0.7.0-beta.1
Updated www.ember-power-select.com

**Comment by terryroe** [comment]
I don't understand the comment after the issue was closed.  There isn't an option to delete the entire tag on backspace, is there?  Has anyone already solved this problem?  I need to implement deleting the entire tag and would welcome a ready solution if there is one.

**Comment by cibernox** [comment]
@terryroe EPS tries to be as agnostic as possible about how a select works. But that said, the default implementations of the single/multiple component have to take some decisions for convenience, and I imitated Select2.js on this one.
 
Instead of providing docens of options to customize every possible flavour of select components (this one would be something like `fullyDeleteLasOptionOnBackspace=true`) I want to expose lower lever primitives to do whatever you want.

In this case you can either use the `onkeydown` event to do something different than the default behaviour, or pass a custom `triggerComponent` that does what you want when you hit backspace. Some tasks can be achieved in more than one way, so there isn't the one and only universal recommendation.

I am aware that it's not totally clear to people not familiar with the addon how to do this stuff, so I'm planing to upgrade the guides and maybe publish a couple of screencasts on how to extend EPS. In the meanwhile [The cookbook](http://www.ember-power-select.com/cookbook) has a few examples that might serve as inspiration.

**Comment by terryroe** [comment]
Thanks Miguel.  I already implemented it using the `onkeydown` approach, which was pretty simple.

**Comment by rhyek** [comment]
Terry, could you show how you did it? Thanks!

**Comment by terryroe** [comment]
rhyek, Here's what I have in my code.  Hopefully it will be obvious to you what's going on.
```
  actions: {
    handleKeydown (dropdown, event) {
      let selected = this.get('selected') || [],
          backspaceHandled = false;

      // Delete the entire last tag if backspacing into the tags area.
      if (BACKSPACE === event.keyCode && isBlank(event.target.value)) {  // BACKSPACE === 8
        this.set('selected', selected.splice(0, selected.length - 1));
        backspaceHandled = true;
      }

      if (backspaceHandled) {
        event.preventDefault();
      }
    }
}
```
I had to copy and fix up some of the code, so this is not directly lifted from my project.  Let me know if you need clarification.

**Comment by rhyek** [comment]
Thank you, Terry. I'm not currently working on that project anymore, but I'm sure it works and I'll definitely come back to this in the future. Again, thanks.

**Comment by cibernox** [comment]
@terryroe That is a perfect example of how to use the actions the components exposes to perform some custom magic and then call `preventDefault` to prevent the usual behaviour  :100:
