### ISSUE TITLE
 Can't resolve 'ember-power-select/helpers/ember-power-select-is-selected & `styles.js` is missing

### ISSUE THREAD

**Issue by bracke** [cibernox/ember-power-select#1738]
I have installed ember-power-select 8 and now the build failes with "Error: Can't resolve 'ember-power-select/helpers/ember-power-select-is-selected'". 
I have followed the migration guide.
Any idea how to resolve this problem?
This is with ember-cli@5.3.0, ember-source@5.3.0. The app is not embroider enabled. 

If I add the missing handler by making a copy of one of the other handlers and renaming it, then I get a different error:
no extension
                Field 'browser' doesn't contain a valid alias configuration
                /tmp/broccoli-9761wfUJ12D91P6/cache-802-webpack_bundler_ember_auto_import_webpack/node_modules/ember-power-select/dist/styles.js doesn't exist
              .js

**Comment by mkszepp** [comment]
@bracke `ember-power-select/helpers/ember-power-select-is-selected` was renamed to `ember-power-select/helpers/ember-power-select-is-equal`

Note: `ember-power-select/helpers/ember-power-select-is-selected` was documented in class as private and also `ember-power-select/helpers/ember-power-select-is-equal` is atm documented as private... but i think we can make it also public, beacuse it is helpful

https://github.com/cibernox/ember-power-select/blob/f54704662c59583f9ae97fdf312b023c8c080cc5/addon/helpers/ember-power-select-is-selected.ts#L1-L22

**Comment by mkszepp** [comment]
> If I add the missing handler by making a copy of one of the other handlers and renaming it, then I get a different error: no extension Field 'browser' doesn't contain a valid alias configuration /tmp/broccoli-9761wfUJ12D91P6/cache-802-webpack_bundler_ember_auto_import_webpack/node_modules/ember-power-select/dist/styles.js doesn't exist .js

Starting with v8.0.0.beta.6 there was missing the `styles.js` export... i will make a fix for that

**Comment by mkszepp** [comment]
@bracke fixed in `v8.0.1` and documented this helper change in migrate docs https://ember-power-select.com/docs/migrate-7-0-to-8-0

**Comment by yaxinr** [comment]
do not work https://github.com/cibernox/ember-power-select-with-create

**Comment by mkszepp** [comment]
> do not work https://github.com/cibernox/ember-power-select-with-create

@yaxinr the addon has as dependency `v7` [see](https://github.com/cibernox/ember-power-select-with-create/blob/56a6e0dce994c0b7c495dfb0721dca34928cea4d/package.json#L34-L39)

Atm the addon is outdated & cibernox is not anymore active on ember. I have maintain rights only some packages from him, so that the most used packages are maintained.
If you are intersted to update the addon to latest `ember-power-select` and also to modernize i can ask cibernox to get permission.

The earier way is to copy the component from addon inside your app and maintain it self.

**Comment by charlesfries** [comment]
@yaxinr Run `ember g helper ember-power-select-is-selected`, keep the generated code as-is, and it should work. It seems `ember-power-select-with-create` depends on that now removed helper, but doesn't call it anywhere from what I can see.

@mkszepp Would you accept a PR that restores that helper in this repo, just to maintain compatibility in the interim? It would be a helper named `ember-power-select-is-selected` that only triggers a deprecation warning

**Comment by mkszepp** [comment]
@charlesfries i don't like to bring back `ember-power-select-is-selected`, because it was always marked in code as private.
But i have now installed in my app the version v2 of `ember-power-select-with-create` and it works without any issue...

Is there maybe inside the own app something which has used this helper?

**Comment by mkszepp** [comment]
I have now also tested inside the `ember-power-select-with-create`. It looks it works also in test-app see https://github.com/mkszepp/ember-power-select-with-create/tree/test-with-eps-v8

**Comment by charlesfries** [comment]
What node version are you on? I'm at `v20.14.0`

I linked a reproduction. The root level `ember-power-select` says 8.2.0, but there is also another `node_modules` under `node_modules/ember-power-select-with-create` that is 7.2.0, and that is the only reference to this deleted helper that I can find.

https://github.com/charlesfries/eps-test
https://github.com/charlesfries/eps-test/actions/runs/9396388125/job/25877468807

**Comment by mkszepp** [comment]
hmm this error is interresting... i have cloned your app and added override for eps, ebs, but in this case with `npm` i run into the next error, that `ember-auto-import` v2 is required... This error is plausible because a v2 addon requires auto import v2 or embroider.
With `pnpm` this error will not displayed, but after that i'm running again in this error...

I will look to get access to the other repo, so we can patch it.

For now you can use my fork `"ember-power-select-with-create": "git+https://github.com/mkszepp/ember-power-select-with-create.git#bc26e2ad4a7b7e8b22a4c003289eef37dd2c1dac",`

**Comment by mkszepp** [comment]
@charlesfries @yaxinr new version for eps-with-create released. its now a v2 addon... if there are any issues, please report on other repo. Thanks
