### ISSUE TITLE
Setting search input onOpen

### ISSUE THREAD

**Issue by kmet31** [cibernox/ember-power-select#266]
Is there anyway to get a handle on the input and default it to the selected text onOpen?

**Comment by kmet31** [comment]
I understand there is a way to go about achieving this through the beforeOptionsComponent, I'll close this issue.

**Comment by cibernox** [comment]
Actually this will probably be fixed tomorrow. 

I'm working on this in this branch: https://github.com/cibernox/ember-power-select/tree/using_the_seach_action_updates_the_seachbox

The issue is that changes in the input trigger the search, but manually calling `select.actions.search('foo')` doesn't update the search. 

After that you will just be able to do 

```js
handleOpen(select) {
  select.actions.search('The text I want to search');
}
```

I've created failing tests, the fix is close.

**Comment by cibernox** [comment]
For now you can, in the `afterRender` queue set the value of the input and trigger an `input` event as a workaround.
