### ISSUE TITLE
Options as an array of objects. Selected as a property of object

### ISSUE THREAD

**Issue by Aaronfischer** [cibernox/ember-power-select#277]
Perhaps I'm missing how to construct the "glue" to make this case work...

I'd like my model attribute to only store a single property (`id`), not an entire object.

However, my API could return an array of objects. This is very useful, as it contains a label as well as an id attribute to decorate the dropdown's options. 
Static example:

```js
statesContent: Ember.computed(function() {
    return [
        {
            id: 'FL',
            label: 'Florida'
        },
        {
            id: 'VA',
            label: 'Virginia'
        },
        ...
    ];
}),
```

```hbs
{{#power-select options=statesContent searchField="label" searchEnabled=false selected=model.state allowClear=true onchange=(action (mut model.state)) as |state|}}
   {{state.label}}
{{/power-select}}
```

This will, by default, set `model.state` to an entire object when I'd really like to keep things much slimmer on the API side and only set it to the state's `id`.

I'm failing to see how this simple use-case is possible.
* Is my assumption correct, there is no way to store a single value but have it reference a larger object? 
* Is there some kind of "glue" I could create to make this translation between a stored property and a larger object work?

**Comment by jcope2013** [comment]
something like this?

``` 

app/helpers/find-by 

import Ember from 'ember';

export default Ember.Helper.helper(function([collection, attrName, attrValue]) {
  return collection.find(el => Ember.get(el, attrName) === attrValue);
});

{{#power-select options=statesContent searchField="label" searchEnabled=false selected=(find-by statesContent 'id' model.state) allowClear=true onchange=(action (mut model.state) value="id") as |state|}}
   {{state.label}}
{{/power-select}}
```

credits to http://miguelcamba.com/blog/2016/01/24/ember-closure-actions-in-depth/

**Comment by cibernox** [comment]
Yes, there is many ways of doing so. 

This component by design works with objects, not ids or labels. By having the object taking only the the information is easy. 

You can use a computed property in the controller/component, a custom action or the snipped pasted above that uses a simple `find-by` helper and the `value` option of closure actions.

Whatever solution works best for your use case.

**Comment by Aaronfischer** [comment]
Fantastic, Thanks @jcope2013 @cibernox !

**Comment by planetexpress69** [comment]
Hi there, similar problem here. I am using a multiple select this way:

`{{#power-select-multiple options=entries  selected=entry placeholder="Select one or more entries" onchange=(action (mut entry)) as |entry|}}
            {{entry.name}}
          {{/power-select-multiple}}`

**Comment by cibernox** [comment]
@planetexpress69 I missed this last week because I was moving home, but the docs are pretty exhaustive: http://www.ember-power-select.com/docs/the-search

You need to pass `searchField="label"` to the component so it know which field to use. Or a custom matcher function if you want to use both. Or even a `search=(action "search")` if you want something even more custom.

**Comment by planetexpress69** [comment]
Thanks Miguel, meanwhile managed to read the doc again and to find the searchLabel as well as the custom matcher. :-)

Thanks again,
Martin

--
