### ISSUE TITLE
Question: Why does beforeOptions willDestroy call search

### ISSUE THREAD

**Issue by cah-briangantzler** [cibernox/ember-power-select#299]
Why does the beforeOptions component [willDestroy](https://github.com/cibernox/ember-power-select/blob/master/addon%2Fcomponents%2Fpower-select%2Fbefore-options.js#L27) call the search method. If the component is being destroyed, I would think not calling search would be preferable.

I found this in a test where I added a debounce that the search was getting called during test teardown and my debounce was being called on a destroyed object. Easy enough to fix with an IF in my code. Was just curious on what calling search in a willDestroy was accomplishing.

Great job on the component.

Thanks

**Comment by cibernox** [comment]
Talking from memory here, but I think that destroying the component calls `action.search` with an empty string. I do that to ensure the search is cleared so the next time the component is opened the results are back to it's original state. 
Searching the empty string is a fast-path that doesn't trigger your custom search action, so it should be synchronous and not cause you any problem. IIRC I added a test to ensure that wasn't a problem.

I think that the problem is not because the `willDestroy` calls the search action but because a debouced search finishes after the component has been destroyed. Perhaps we should guard agains that.

Can you get an example?

**Comment by cah-briangantzler** [comment]
Oh its definitely my debounce code and I have a check to make it work, was just wondering why there was a call to search during the destroy code. Based on your explanation, and looking at the code, I infer that when "search" is used, there is a minimum of 1 char before the search is invoked. I had assumed that the search would still be called with an empty term.That is to say I thought the search was allowing me to do the search wether it be a promise or just a complicated search, but I did not infer that there was a one char minimum. May want to update the docs accordingly

**Comment by cibernox** [comment]
@cah-briangantzler I've updated the docs about the search to clarify that clearing the search restores the initial state of the select without triggering the search action.

I agree that it might be a bit unexpected, but in exchange makes some usage patterns simpler.

**Comment by cah-briangantzler** [comment]
Thanks
