### ISSUE TITLE
Change color of selected and current options

### ISSUE THREAD

**Issue by matthellstrom** [cibernox/ember-power-select#317]
I've created a custom class for my app, and I'm having trouble changing the color on selected and current options. I'm able to do it, but I'm pretty sure it's not the right way to accomplish it.

Here's the code I have:

  .custom-eps {
  }

  .custom-eps-dropdown {
    line-height: 1.5;
    font-size: 0.80em;  
  }

  .custom-eps-dropdown > ul > li {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;    
  }

  .custom-eps-dropdown > ul > li[aria-selected="true"] {
    background-color: #2c3e50;
    color: #ffffff;   
  }

  .custom-eps-dropdown > ul > li[aria-current="true"] {
    background-color: #2c3e50;
    color: #ffffff;   
  }   

  .custom-eps-trigger {
    margin: 2px;
    color: black;
    padding-right: 35px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis; 
  }

It seems to work just fine, but I think it's wrong using aria-selected and aria-current to set the colors. Is this the best way, or if not, what's a better one?

Also, I don't really want to override the actual css, as I'd like to customize it differently in different parts of my app.

**Comment by cibernox** [comment]
It is perfectly fine to target aria roles for styling. Actually is even advised as a good practice by the ARIA-WARIA guidelines and I intentionally don't have special classes for highlighted/selected elements to enforce people to build accesible select if they customize them.

If you don't want to change the color globally using the sass variables, your approach (passing a `class="custom-eps" that then becomes `.custom-eps-trigger` and `custom-eps-content`) is correct, although probably you don't need selectors with such a high priority.

I'd probably just use `.my-custom-class-dropdown .ember-power-select-option[aria-current="true"]` and
`.my-custom-class-dropdown .ember-power-select-option[aria-selectec="true"]` for styling.

As a rule of thumb is generally better to target classnames/attributes instead of tags tags, and use the descendant selector (`>`) with caution, because if I ever decide that I need a wrapper div or something the selector is broken.

**Comment by matthellstrom** [comment]
Perfect! Didn't know quite how to do it, thanks for the help!
