### ISSUE TITLE
Optional entry of creating a new item in the list

### ISSUE THREAD

**Issue by hotterd** [cibernox/ember-power-select#327]
There is already a very useful feature of displaying an empty state when the list is empty.

I'm thinking wether it would be good to go further and add another useful feature, which displays a "New..." entry at the bottom of the list, perhaps in another group. It can aways show in the list no matter the list is empty or not, even when displaying search result. When the entry is selected, an action is sent, e.g. newListItem, allowing user to handle the event, such as rendering a modal and/or mutate the list.

Any thoughts on this?

**Comment by cibernox** [comment]
Check the addons section: https://github.com/cibernox/ember-power-select-with-create

**Comment by hotterd** [comment]
Thanks! This is great. I did not notice this. Although it seems cannot display the Add entry in the dropdown list when not typing in search, I think I can overcome that with specifying the placeholder text as "Type to Search or Create New..." or something similar, to give user a hint.

**Comment by cibernox** [comment]
Well, makes sense because you need to type something in order to be able to create it. 

There is a few ember-power-select addons already, listed here: http://www.ember-power-select.com/addons

If you ever create another, add `ember-power-select-addon` to the keywords section of your package.json, so I can automatically discover community-built meta addons.
