### ISSUE TITLE
Acceptance Testing

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-power-select#358]
Upgrading from 0.8.6 to 0.9.1 (w/ no other changes other than some of the breaking api changes) doesn't allow acceptance tests to click a power select single dropdown; however, clicking the dropdown for a multiple power select works in acceptance test land.  Everything is g2g in development mode though.  Couldn't write a failing test for a pull request either.  Also tried using the selectChoose helper as well, but didn't have any effect.  Any thoughts? Thought all tests passed earlier today...

**Comment by snewcomer** [comment]
Just tried on another app and upgrading from 0.9.0 to 9.1 gives me the same failures.

**Comment by snewcomer** [comment]
Installing a new set of npm modules and moving back to 0.9.0 causes my tests to fail (passed before upgrade to 0.9.1.  Hmmmm...

**Comment by cibernox** [comment]
@snewcomer That makes sense because I released a new version of ember-basic-dropdown with support for touch gestures yesterday, and EPS depends on EBS with a related operator `^`.

It should be backwards compatible, but apparently I've screwed something. 

You can co back to 0.9.0 and add ember-basic-dropdown locked to 0.9.1 (the bug was introduced in 0.9.2).

Questions: Are you using the test helpers provided by EPS?
Browser used in tests (or phantomjs)?

**Comment by cibernox** [comment]
Ok, I found it. It turns out that I missed a but because I develop in beta and this was an issue only in Ember <= 2.4, because test helpers fire jquery events, and jquery events don't trigger event handlers added with `addEventListener`.

Install 0.9.2 and all should be ok.
