### ISSUE TITLE
Clicking remove button - acceptance tests

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-power-select#385]
Having trouble clicking the remove button for multiple inputs in my acceptance tests.  This change came after the 0.9.0 release.  I guess I am trying to understand the reason why my basic css selectors of clicking the dropdown, selecting an option and removing an option don't work anymore (it seems dispatchEvent is req'd).  I have to use the test helpers, which are great, but don't know the why.  Maybe a bit of an explantion or thoughts on a solution to the above would be greatly appreciated.  Maybe some insight could help me in perhaps getting a new test helper in there as well!  Thanks!

**Comment by cibernox** [comment]
This is an issue with ember 2.4 that is fixed in ember 2.5+.

The problem is that Ember's acceptance helpers fired jquery events (not native events) until [this PR](https://github.com/emberjs/ember.js/pull/12575). 
This is fundamentally wrong, since jquery event's do not trigger events added with `addEventListener`.
Events added as element properties `onclick={{action "foo"}}` are also busted since, unless you call preventDefault on them, they are considered unhandled and will fire twice.

Using Ember 2.5-beta should also be fine. If you are using the helpers provided by the addon (p.e `selectChoose`) you're fine because I already take care of the details of how events are fired, although there is no test-helper for removing events in multiple selects. 

I'd accept one test helper for that tho.

**Comment by snewcomer** [comment]
https://github.com/cibernox/ember-power-select/pull/400
