### ISSUE TITLE
When tabbing through multiple power selects, the input does not get focused if the select opens on focus

### ISSUE THREAD

**Issue by MartinMalinda** [cibernox/ember-power-select#394]
I guess this is a marginal usage of power-select, but I have multiple power selects on one page and I want to be able to pick values by keyboard as fast as possible. That's why I call select.actions.open() in onfocus(). But for some reason I have to press tab twice for each power-select to be able to type into search input. First tab press makes only the select to open, not focus. 

There's an example in https://github.com/MartinMalinda/ember-power-select on /multiple.

**Comment by MartinMalinda** [comment]
Issue can be sort of solved this way:
```hbs
{{#power-select 
onopen=(action "selectOpened")
```
```javascript
selectOpened(select){
  run.later(() => {
    $('.ember-power-select-search input').focus();
  }, 0);
}
```
Without the run.later, tabbing tends open multiple selects at once.

**Comment by cibernox** [comment]
I'd expect the focus to work out of the box. I'll check it.

**Comment by cah-briangantzler** [comment]
I have subclassed power-select and added a openOnFocus property that pretty much does this without having to monitor for an action every time. If you would like this as a PR I can submit it. Its just a few line change

**Comment by cah-briangantzler** [comment]
As far as the tab twice to advance. I played with this extensively one weekend. Normally the dropdown is rendered in ember wormhole. When the drop down is closed there is a run next that refocuses the power-select. There is a way to make it NOT refocus the power select and allow the tab to continue on to the next field. However since its rendered in worm-hole the next field in tab order is NOT what you want.

I found no easy way to make what you want to happen automatically. (Note also power-select currently doesn't select on tab)

I have a bad way of doing this, but its really bad and still looking into a better way.

**Comment by cibernox** [comment]
I was aware of the problem when transfering focus from some input inside the dropdown to the next focusable element after the trigger. There must a way of doing that.

**Comment by cah-briangantzler** [comment]
I was able to intercept everything and it can down to having to send a tab in a run next after everything has shaken out. However, due to security constraints I found no way to send a tab. The next solution was  a jquery component that searched the dom for the next field after this one that was enterable and focued to that. The code was extensive and I wasnt sure I wanted to include that into the component. Also not sure it took tab index into account.

Currently I have a few ideas, but no good solution

**Comment by cah-briangantzler** [comment]
Did you want a PR for openOnFocus and selectOnTab. I would love these in the base power-select component instead of having to subclass.

Min chars to search and debounce are the other two reasons I subclass. Would love these in the base as well. (Proposed those earlier but at that time you felt they should be in separate addons? user implements them self?)

**Comment by cibernox** [comment]
@cah-briangantzler No, I left the open on focus as an exercise to the user (I even have an [example] here(http://localhost:4200/docs/action-handling)) to bake in as little functionality in the core as possible. 

Your solution of creating another component that extends (or wraps) EPS to match your personal flavour of selects is precisely what I'd like people to do. Create they own branded component using EPS as a base.

It can be a separated addon if you want :+1:

**Comment by cah-briangantzler** [comment]
I understand.

If a lot of people need the same functionality though, they have to keep creating it over and over again.

Your examples are at time of use, so if they need the same functionality on multiple screens, they have to duplicate the code, or subclass as I have.

Making it an add-on works till I have feature 1 in my add on and someone else has feature 2 in their add-on and I as a user want both features….
Or possibly they have subclasses and want an add ons features are well.  Cant have both.

I do understand though the base component can’t be everything. But if it can support a feature relatively easier, shouldn’t it?

But anyway. I have subclassed and will keep bugging you from time to time about it :)

**Comment by cibernox** [comment]
@cah-briangantzler The line is always blurry. As a maintainer, I biased towards having the least amount of baked in functionality, but if people keep requesting this I might just surrender to public opinion :sweat_smile:
