### ISSUE TITLE
Overriding focus-border-color does not seem to work

### ISSUE THREAD

**Issue by terryroe** [cibernox/ember-power-select#397]
Attempted with versions; 0.9.0, 0.9.2, 0.10.0-beta.4

I've added the following variable overrides to my project:
```
$ember-power-select-border-color: red
$ember-power-select-focus-border-color: blue
```
As you can see in the screenshot, the border with input focus is still red, but should be blue.  Am I doing something incorrectly, or are the variables in the ember-power-select project not working correctly?
<img width="576" alt="screenshot 2016-03-22 10 01 21" src="https://cloud.githubusercontent.com/assets/59881/13958265/129e199e-f015-11e5-9412-1dc63a684316.png">
I also tried setting the specific border variable as well, and it didn't seem to have any effect.
```
$ember-power-select-trigger-focus-border: 1px solid blue
```
Thanks, TR

**Comment by cibernox** [comment]
Sorry for the delay, I've been in holidays the last weeks.

I see your issue. 

The problem is that `$ember-power-select-focus-border-color` is the color of the border of the trigger when it is focused. But in the case of multiple selects, when you focus the component you are actually focusing the input inside, not the trigger.

I have to find a way a way of styling "active" selects (when "active" means the component or any of it's children has the focus).

**Comment by cibernox** [comment]
I've added a feature to the component to handle this. Check PR #424.

This was something I had in my backlog anyway.
