### ISSUE TITLE
Long option names overflow outside the select box

### ISSUE THREAD

**Issue by kevinkucharczyk** [cibernox/ember-power-select#413]
If the selected option's name is longer than the width of the select box, it will overflow outside of it, like so:

![screenshot](https://cloud.githubusercontent.com/assets/3127419/14141631/98411bfc-f680-11e5-8e94-4293f8c5c343.png)

The text should be cut off (perhaps with an ellipsis) before the "clear selection" and arrow buttons.

**Comment by cah-briangantzler** [comment]
This should be easy to fix now that there is a span about the yielded text. Note however that the clear and dropdowns icons are absolute positioned so you will have to put some padding or something on the span to allow room for them. Would be nicer is the clear and dropdowns were actually additional spans instead of absolute positioned, then when there was no allow clear the text would be able to use that additional room
