### ISSUE TITLE
Options displayed as undefined momentarily

### ISSUE THREAD

**Issue by jakeleboeuf** [cibernox/ember-power-select#417]
Besides being obnoxious seeing the quick flash of `undefined`, I'm trying to apply a simple helper that converts `_`'s to spaces, but each item is rendering as `undefined` at runtime.

Is there something whack with my setup, or is this something that needs to be addresses?

![undefinedcolors](https://cloud.githubusercontent.com/assets/690573/14162327/05cfb7c2-f6b9-11e5-95a5-d390051e5b27.gif)

**Comment by cibernox** [comment]
@jakeleboeuf I don't think that this has to do with ember-power-select.

The most probable thing is that your options are models and the property your are trying to sanitize belongs to some asynchonous `belongsTo` relationship, and while those models are fetched your helper displays undefined.

In other words, you'd have the exact same problem if instead of EPS your were using a simple `{{#each}}`

**Comment by jakeleboeuf** [comment]
Yea man- I think that's exactly what's happening. I'll clear this issue and see what I can do to tackle it. Thanks!
