### ISSUE TITLE
Hovering mouse over scrollable list interferes with keyboard navigation

### ISSUE THREAD

**Issue by aquamme** [cibernox/ember-power-select#429]
To reproduce this issue:
1) Open an ember-power-select list with enough options that a scroll bar is shown
2) Hover the mouse cursor over an entry
3) Use arrow keys to navigate far enough down the list that the scroll position changes
Result - upon scroll position change, the highlighting jumps to the element that the mouse cursor is hovering over

This can be reproduced using any of the examples from the [action handling](http://www.ember-power-select.com/docs/action-handling) page of the docs.

**Comment by cibernox** [comment]
Yeah, I noticed this myself before but it's not easy to fix, and much less to simulate in tests.

The reason is that when the content scrolls and the option below the mouse changes a new `mouseover` event is fired, which highlights the option.

My vague plan is something like track the last coordinates of the mouse and if a `mouseover` is fired but the mouse hasn't move at all, disregard the event.

I'll tag it as a bug so I don't forget about it, but it's not top priority for this week.

**Comment by anehx** [comment]
What's the status on this one?

**Comment by DSheffield** [comment]
Why closed?  The problem still seems to be present.
