### ISSUE TITLE
Use of `onfocus` doesn't allow for the default behavior to be overridden

### ISSUE THREAD

**Issue by aquamme** [cibernox/ember-power-select#435]
It doesn't appear to be possible to prevent the dropdown from toggling when clicking in the input box.

For example, this code has no effect:

```
handleFocus (dropdown, event) {
  event.preventDefault();
  event.stopPropagation();
}
```

Tested with
Ember 1.13.10
EPS 0.9.0, 0.10.0-beta.8

**Comment by cibernox** [comment]
That is true, clicking on the trigger is one of the few events you cannot hijack in the select. It is quite intrinsic to the default behaviour of a select, so it's not configurable.

You can however pass a custom trigger component, capture the `mousedown` event on it and prevent it from bubbling.

**Comment by cibernox** [comment]
I'm going to close this one, since it can be done providing a custom trigger component that reacts to mouse interaction in a different way. 

But as default behaviour, toggling on click is so common that I don't think it worth the effort to make it configurable with a dedicated option. 

I just have to draw a line somewhere on what deserves its own configurable option and what can be done but in a more involved way (creating your own custom trigger component).

Let me know if you need help implementing a custom trigger component for this :+1:

**Comment by aquamme** [comment]
Thank you! I appreciate the offer and the information.
