### ISSUE TITLE
How to prevent clearing of input box on click?

### ISSUE THREAD

**Issue by aquamme** [cibernox/ember-power-select#436]
After entering text, if the user clicks outside the dropdown list (including the input box), the text is cleared. Is there a way to leave the text intact?

**Comment by cibernox** [comment]
No at the moment. When the component is closed the search term is wiped. 
And that sounds like something that wouldn't be easy to implement actually with the existing hooks.

**Comment by cibernox** [comment]
I'm sitting on the fence with this, but it might be something that worth to make customizable.

**Comment by aquamme** [comment]
For reference, I'm building an omnibox. The behavior I'm aiming for is essentially that of chrome's address bar, but with multiple selection.

**Comment by cibernox** [comment]
That is actually doable. More than doable, it's done-ish. 
Ember-power-select-typeahead might be what you want, or at least is similar enough to take it as inspiration.

The repo is https://github.com/cibernox/ember-power-select-typeahead
Here there is a live demo: https://ember-power-select-typeahead.pagefrontapp.com

What is hard to do is not wipe the text in a seachbox inside the floating box, because that component will be destroyed when the select is closed. But if the input is in the trigger then it's easy.

**Comment by cibernox** [comment]
I'm closing this since there is already some examples of how to do that in the wild.

Let me know if you still struggle with that.
