### ISSUE TITLE
Detect when the trigger input field is blank

### ISSUE THREAD

**Issue by terryroe** [cibernox/ember-power-select#465]
We need a way to reliably determine if the trigger input field is blank.  I've reviewed the other issues here for key-down, key-press and using the search function to detect the text, but none can be used for notification when the input field becomes blank.

The reason for the need is probably not important, but I will detail it here in hopes that a solution will come to mind:

We've implemented a type-ahead feature by using a second input field directly underneath the trigger input field.  When text is entered into the trigger, we display the full text of the selected item in the second input field making it appear like the text is auto-filled.

We are also trying to use the secondary input, type-head field for displaying the placeholder text because the placeholder has been removed from IE.  We need the placeholder text in IE (but we are glad that its removal fixes problems with the dropdown in IE).  I think we can use the secondary placeholder successfully if we can determine when the trigger input is blank/non-blank.

**Comment by cibernox** [comment]
Although is not in the docs because is relatively new and I haven't updated them, there is an `oninput` actions that is fired when the searchbox changes its content. Unlike the `search` action that is not fired (intentionally) when the searbox is cleared, this action is fired.

The signature of the actions is `(text, publicAPI, event)`. 
If you have more than one input as you mention you can probably use `event.target` to know from which one the event comes from.

I'm sorry about the placeholder in IE10. IIRC there is a bug that microsoft won't fix that when a placeholder is added the input emits an onchange action (which is wrong), so I had to disable it for IE.
I don't remember if it was in all IE or IE11 is ok.

**Comment by cibernox** [comment]
I've just checked and this is the commit message of the commit where I disabled the placeholder for IE:

```
    Disabled placeholder of multiple selects in internet explorer 10 & 11

    There is some kind of bug in IE that causes the input to gain the focus over and
    over when it has placeholder.

    This solution is less than ideal, but it's better to not have placeholder than
    to have a select that you can't close.
```

In any case, let me know if the `oninput` action works.

**Comment by terryroe** [comment]
Miguel,

Thank you for your help.  Yes, `oninput` works, but I also had to use `onclose` to detect when focus is lost. The input field gets emptied when you click outside it, but `oninput` isn't triggered in that case.

I knew the reasons for disabling the placeholder, and agree that it was needed to get around IE's problems.  But I now have a solution for type-ahead, as well as placeholder text in IE.

Thanks again,

TR

**Comment by cibernox** [comment]
👍
