### ISSUE TITLE
Should pressing Enter open the dropdown?

### ISSUE THREAD

**Issue by shripathee** [cibernox/ember-power-select#519]
In a number of scenarios, Power Select is used within a form. The general behaviour in a form is that pressing **Enter** performs the Submit action. Hence, pressing Enter when the Power Select is in focus simultaneously opens the dropdown while saving the form. Already, we have **Down Arrow** and **Space** for opening the dropdown. Is it possible to remove the **Enter to open** functionality or move it under a flag?

**Comment by cibernox** [comment]
Opening on enter is the default behviour for native selects, so that's why I think t should be the
default behaviour of this component too. Native selects inside forms also open and submit the form
at the same time when enter is pressed.

That said, you can prevent pretty much any default behaviour if you `return false;` from any of
the actions of the component: [Docs](http://www.ember-power-select.com/docs/action-handling)

In this case, just provide an `onkeydown` action

```hbs
{{#power-select ... onkeydown=(action "preventEnter")}}
```

```js
preventEnter(select, e) {
  if (e.keyCode === 13) {
    return false;
  }
},
```
