### ISSUE TITLE
Unclear on how to pass the value to be displayed to a custom optionsComponent

### ISSUE THREAD

**Issue by Yathi** [cibernox/ember-power-select#554]
I am trying to implement my own _optionsComponent_ because I want to implement a nested layout with checkboxes. I also want to be able to click on the parent of the option tree to select all the child options. But I am unclear on how I can pass in the value of the options to a custom ember component. 

An example in the documentation on how to implement a custom _optionsComponent_  would be great.

**Comment by cibernox** [comment]
Yes, the options dropdown is the most complex one to implement. The only example similar to that is http://www.ember-power-select.com/cookbook/navigable-select

If you are going to implement this, I advice you to do it in 1.0.0-alpha.2 or greater. I've been simplifying the public API received by sub-components, concentrating all the information an actions that I consider public in a single object, named `select`.  I reckon that this process is 70% done.

The public API of that object is here, at the bottom: http://www.ember-power-select.com/docs/api-reference

For now, only attributes and actions inside this object is considered public API (unless they start with underscore). This object will probably grow, but I don't expect any property or action that is there to disappear or change its name. 

Maybe that public API object is enough to implement what you want. If not, all feedback is welcome, since the plan is dogfood the public API and eventually only rely on it.

**Comment by cibernox** [comment]
I'm going to close this since it's not a real issue and it will have to wait for the public API to be defined and documented before creating entries in the cookbook, but feel free to keep posting in this closed issue if you have feedback.
