### ISSUE TITLE
Pressing Enter in power-select-multiple does not prevent the default event from occuring

### ISSUE THREAD

**Issue by ultimatemonty** [cibernox/ember-power-select#567]
Ran into a situation where pressing Enter to select an option in power-select multiple does not prevent a form submission. A rough example would be

```
<form {{action 'save' on='submit'}}>
  {{#power-select-multiple
    onchange=(action 'selectedItemChanged')
    options=options
    as |option|
  }}
    {{option.text}}
  {{/power-select-multiple}}
</form>
```

In this scenario pressing Enter to select an option selects the option and then submits the form. 

Played around with it and confirmed that adding `e.preventDefault()` after the `e.stopPropagation()` calls [here](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select-multiple.js#L38-L420) fixes this.

Happy to submit a PR if you think it's worth it.

**Comment by cibernox** [comment]
That behaviour is expected and intended. I considered calling preventDefault because I also found it a bit annoying, but pressing ENTER on native `<select>` behaves the same way (submits the form) so I decided to let it to the user to as aligned with regular selects as possible.

What I do instead is `{{#power-select-multiple ... onkeydown=(action "preventDefault")}}`. It requires very tittle code.

**Comment by ultimatemonty** [comment]
@cibernox pressing Enter on a regular power-select does not submit the form though.

I initially tried something like
```
onkeydown(options, e) {
  if (e.keyCode === 13) {
    e.preventDefault();
  }
  options.actions.handleKeydown(options, e);
}
```
which ends up in a recursive loop and things go 💩  in a hurry. How are you handling that?

**Comment by cibernox** [comment]
Pressing Enter on a regular select if it doesn't have a searchbox or it has a searchbox but it's rendered in-place submits the form. The reason why it doesn't submit the form when it's not rendered in place is because the input is attached to the root of the app, so it isn't physically inside the form and the event doesn't bubble to it.

The only thing I do is 
```hbs
{{#power-select-multiple onkeydown=(action "preventDefaultEnter") ... as |opt|}}
```
```js
preventDefaultEnter(options, e) {
  if (e.keyCode === 13) {
    e.preventDefault();
  }
}
```

**Comment by ultimatemonty** [comment]
@cibernox ahh that totally makes sense. I was overriding `onkeydown` which is why I was having issues.  Thanks!
