### ISSUE TITLE
Add less support

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#57]
Apparently it is possible to translate from sass to less with not much effort, so this might come handy for someone.

The workflow would be:
- The styles of the addon are coded in Sass as usual.
- The same `compile-css.js` script that is used to transform the .scss files to .css ones and move them into `vendor` can be used to also transform them into .less files.
- Unlike .css files, .less files should not be placed inside vendor but inside `app/styles`, next to the sass ones, so the user can import them as usual.

**Comment by MojoJojo** [comment]
@cibernox Is anyone working on this? I can pick this up..won't take more than a few hours I suppose..

**Comment by cibernox** [comment]
No, no work has been done on this yet, and all help is welcomed. 

Check the `compile-css.js` file and the `index.js` files for the relevant info.

**Comment by cemarte** [comment]
Hi @cibernox ! Any news about this enhancement? I could help if you want.

**Comment by cibernox** [comment]
@cemarte Please, help would be welcome. As far as I know nobody started any work on this, and I don't use less myself.

Basically the task consists in improve the `compile-css.js` to iterate over each `.scss` and transform them into `.less` files. I guess that there must be some library that does that.

**Comment by cemarte** [comment]
@cibernox could not find any npm package that does the direct convertion from scss to less.I thought it would be easy to find a reliable library for the purpose ... are there other options e. g. manually  generate a less in your addon project and maintain it? Or (It hurts) do a scss-css-less?

**Comment by cibernox** [comment]
@cemarte There is something called grunt-refactor that I think that can do the transformations.

scss -> css -> less is not an option. Variables, which are per se the main advantage of the scss approach would be lost in the process.

It it cannot be automated, it would need to be done manually. Although since I'm not really using any advanced sass features, I think that the transformations could almost be done vía regexp.

**Comment by cemarte** [comment]
Yes, got it! Can I send a PR?

**Comment by cibernox** [comment]
Absolutely

**Comment by simonihmig** [comment]
Seems nobody has really tackled this so far. Need this now for a project and already did a conversion of ~90% *manually*.

The idea of having Scss automatically transpiled to Less seems interesting at first. But I think it is practically not feasible. There are things that are identical (nesting), some are probably easy to transpile (variable definitions), but other are very hard (loops) up to plain impossible. And it seems there is no lib that can do this (at least the possible parts), or I don't know of any.

And the only real benefit would be if you would be able to transpile 100% of Sass features (which is as I said impossible). Otherwise you would either have to maintain the Less code manually (when no conversion is in place) or maintain the conversion (when there is one and new Sass features get used). With the latter being a much greater effort I think!

So I would vote for a manual Less migration, that maybe needs some occasional maintaining whenever the Sass code changes. @cibernox would that be ok for you?

Could file a PR for this, when I have finished the remaining 10%...

**Comment by miguelcobain** [comment]
Another option that occurred to me was to create a new addon that includes eps and adds less support if ember-cli-less is present (or whatever method we use to detect less).

**Comment by simonihmig** [comment]
@miguelcobain Certainly possible. But then why is Sass support part of eps and Less not, other than personal preference? ;) 

My idea was to also add a modified default blueprint that adds (or better amends the existing) `app.scss` or `app.less` based on the available preprocessor. Did annoy me a bit that I found a new `app.scss` in my Less project. ;) So eps is not opinionated about the used preprocessor and installs the appropriate files based on the project.

**Comment by miguelcobain** [comment]
@simonihmig good point. I agree with you.

**Comment by cibernox** [comment]
@simonihmig Yes, I chose Sass just for personal preference (and popularity). I author the styles in sass and then transpile them to css as a prepublish step.
The steps to make less a first class citizen are not that hard:

- Make Less a first class citizen in ember-basic-dropdown.
- Create an `ember-power-select.less` in the same folder than the `ember-power-select.scss` file.
- Update the `index.js` file. Where right now we check for the presence of `ember-cli-sass` we will need to check also for the presence of `ember-cli-less` or whatever addon is the default standard.
- Change the blueprint to modify the `app.sass` or `app.less` file depends on the addon being used.

If the translation from sass to less cannot be automated it's a shame but it should be that bad now that the addon hit 1.0. I don't think that the styles will change until 2.0. Seems like something we can maintain manually.

**Comment by simonihmig** [comment]
Cool, sounds good. Expect a PR hopefully soon...
