### ISSUE TITLE
Knows the selected Item that it is the selected one?

### ISSUE THREAD

**Issue by Haidy777** [cibernox/ember-power-select#605]
```handlebars
{{#power-select}}
    {{#if isSelected}}
        <span>some extra text</span>
    {{/if}}
    {{item}}
{{/power-select}}
```

Is there a way to add the 'extra text' only when the item is the current selected (= the one shown in the trigger).

I tried a computed-property for the "selected"-property (which has 'isSelected'), but that leads to the problem that the "inline"-highlighting ('aria-selected') won't work anymore.

Sorry for the title, but I couldn't think of a better one ;)

**Comment by cibernox** [comment]
Using ember-truth-helpers is simple, since the selected item is in your scope.

```hbs
{{#power-select options=options selected=selected as |opt|}}
  {{#if (eq opt selected)}}
    Some text
  {{/if}}
  {{opt}}
{{/power-select}}
```

If by example, you want to do it with the highlighted element, something that is not a property in your template you also can. The block receives two arguments, the item and the publicAPI, which contains all the state of the component (see the bottom of http://www.ember-power-select.com/docs/api-reference)

So, you can:

```hbs
{{#power-select options=options selected=selected as |opt select|}}
  {{#if (eq opt select.highlited)}}
    ->
  {{/if}}
  {{opt}}
{{/power-select}}
```

You should probably also use this approach even for the first case even if the selected element is in the template: 

```hbs
{{#power-select options=options selected=selected as |opt select|}}
  {{#if (eq opt select.selected)}}
    ->
  {{/if}}
  {{opt}}
{{/power-select}}
```

The reason is that if `selected` is a promise (a `belongsTo` relationship by example)  the `(eq opt selected)` is going to fail, however the `select.selected` property will take care of unwrap the promise and you can safely do the comparison.
