### ISSUE TITLE
Select is not disabled in disabled fieldset

### ISSUE THREAD

**Issue by ktrhn** [cibernox/ember-power-select#656]
Form elements in a fieldset with the disabled attribute are disabled automatically (without the need to specify disabled for every element). This does not work for ember power selects.

**Comment by miguelcobain** [comment]
So, the disabled property should depend on something like `this.$().closest('fieldset').prop('disabled')`?
Maybe we could make it a computed property which returned that by default.

**Comment by cibernox** [comment]
This one is tricky. Since that property would accessed while the component is not yet rendered, its parent will probably still being rendered and and it wouldn't work. Besides, it makes me a but uncomfortable having to access and read the DOM in order to render this component, and that is also a problem if the fieldset gets enabled later on and the component doesn't realized.

And setup a MutationObserver on the hypothetical closest fieldset seems overkill.

I feel inclined to assume that the user has to tell the component when to disable/enable. Seems too much work for such an edge case.

**Comment by ktrhn** [comment]
Seams reasonable. Maybe a note in the documentation about this?
