### ISSUE TITLE
Perform some action when arrow is pressed over a focused select?

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#69]
Apparently there is no consensus about that even in native elements

* In webkit/blink pressing down or up opens the list of options (and from that point on behaves as expected)
* In firefox pressing up/down selects the previous/next option but without opening the list
* In selectize.js pressing down opens the list but pressing up does nothing (however the event is highjacked because it prevents the page from scrolling)
* In select2 nothing happens and the page scrolls

![fuu](https://media.giphy.com/media/ADr35Z4TvATIc/giphy.gif)

/cc @miguelcobain

**Comment by miguelcobain** [comment]
> In webkit/blink pressing down or up opens the list of options (and from that point on behaves as expected)

I'm on linux chrome and I see a different behavior. When I focus a select, down and right arrows advance to the next option and up and left arrows go back one option, without opening the dropdown. (Pretty much like your description of firefox).

Examples: http://getbootstrap.com/css/#selects

Have you tested on chrome as well?

**Comment by cibernox** [comment]
Weird, I don't see that using this: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

http://quick.as/1aW4Ca33z

This is chrome: Up and down arrows open the list. Right and left do nothing.

**Comment by miguelcobain** [comment]
Must be an OSX/Linux thing.
That example doesn't behave at all like that here.

**Comment by cibernox** [comment]
If the behaviour of a select is OS specific this is still even more WTF for me.

What seems clear is that arrow keys should do something. Just not sure what.

**Comment by miguelcobain** [comment]
My thoughts on this:

> In select2 nothing happens and the page scrolls

Could be preferable if, in some scenario, the scrolling is more important than the selection. However I feel that this would be an edge case, if any at all. So basically I think we should ignore this.

> In firefox pressing up/down selects the previous/next option but without opening the list

This is better, but not ideal, since the user still has to "guess" what the next/previous option is. Opening the dropdown gives more context of the surrounding options to choose from. So, I'd rather have the dropdown opening than this.
> In selectize.js pressing down opens the list but pressing up does nothing (however the event is highjacked because it prevents the page from scrolling)

> In webkit/blink pressing down or up opens the list of options (and from that point on behaves as expected)

I think that webkit **(on osx, at least)** got it right. Selectize should also use the up arrow, IMO.

In a nutshell, IMO, when the select is focused:
- pressing down should increment the selected index
- pressing up should decrement the selected index
- if nothing is selected, pressing down makes selected index `0`
- if nothing is selected, pressing up makes selected index equal to `options.length` (basically selecting last option)
- I think it wouldn't hurt (near zero overhead) to pair down/right and up/left keys. Some people, by some reason, may be accustomed to left/right keys.

Open questions:
- should the arrow keys just highlight and then expect the user to press enter to select the option, or should they select immediatly (triggering onchange)?
- how should be the behavior in multiple selects? Selectize seems to do exactly as explained above.

I think that selectize should be used as a reference, except on that little "up" key detail. Its defaults feel really right to me.

**Comment by cibernox** [comment]
When the list of options is visible up and down I think that already work as expected, so nothing to do that.

When the list of options is not visible but the trigger is focused probably both up and down should make the list of options visible, but the selected element is the one highlighted. This is how things usually work, so the only change is show the list of options (like if you pressed enter).

In case there there is nothing selected, I think that the first element of the list should be selected both for the up and down arrows, mostly to just copy chrome on OSX.

Still not convinced about left and right, so I won't implement them for now.

**Comment by miguelcobain** [comment]
I'm totally ok with that.

What about multiple selections?

**Comment by cibernox** [comment]
@miguelcobain Multiple selections work the same. Closed by #70
