### ISSUE TITLE
Add Custom Option

### ISSUE THREAD

**Issue by cottrellio** [cibernox/ember-power-select#72]
Is there currently support for adding a custom option similar to the `create-item` action on `ember-cli-selectize`?

**Comment by miguelcobain** [comment]
This is also a use case I will need.
Basically, tag support, @cibernox.

**Comment by cibernox** [comment]
It will land, probably next week, but probably not like an magic config option but as an action you can implement :)

**Comment by miguelcobain** [comment]
Sure.
But we need to display some text in the dropdown, don't we?
Like "Create {{text}} option".

**Comment by cottrellio** [comment]
Yeah that would be nice.

**Comment by catataw** [comment]
+1

**Comment by felixkiss** [comment]
> It will land, probably next week

@cibernox What is the timeline on this feature? I couldn't find it in the CHANGELOG up to `0.6.0-beta.4`, so I assume it was delayed. What are the reasons?

**Comment by cibernox** [comment]
@felixkiss This is the PR: https://github.com/cibernox/ember-power-select/pull/150

Basically I added on `onkeydown` action that you can use to do whatever you feel like. The most obvious use case is detect that the user pressed enter, take the text of the event's target and create a new option with it. Typical select that allows to create new tags on the fly.

I'm sitting on the fence about that is the best way of preventing the default behaviour (close the select on enter by example). Will be merged today.

**Comment by cibernox** [comment]
Closed via #150

**Comment by felixkiss** [comment]
@cibernox 

I would like to implement behavior as seen in [ember-cli-selectize](https://github.com/miguelcobain/ember-cli-selectize):
![screen shot 2015-11-29 at 22 07 27](https://cloud.githubusercontent.com/assets/256075/11460093/2e969a32-96e6-11e5-8610-dbd395ebfe92.png)

- Show option `Add <current search term>...` above search results

Can you give me a hint on how to accomplish this? I think I would need the following:

- Ability to inject a template for an additonal search result item (in this template, I need to have access to at least the current search term, to not show `Add ...` on empty search term)
- Ability to select this custom search result item as any search result item (up/down arrow keys work; enter = selection)
- Upon selecting this custom search result item, an action should be fired
- Visual distinction between existing search result items and this custom create item would be really nice to have. Selectize really does a great job on this.

**Comment by cibernox** [comment]
Sure, I think that did a similar example somewhere. Let me search...

**Comment by cibernox** [comment]
I didn't. I tried to create a working example now in 10 minutes in this repo following what seemed the simplest approach: https://github.com/cibernox/eps-add-option-tmp

This kind of works but it's not perfect, because after selecting the option we should be able to clear the search, and at the moment the dropdown object received by the `onkeypress` action does not exposes tat function. 

So this is an area where this component should improve. I must expose actions to clear that.

In general in this case I'd do:

1. You have a list of options, with the real options
2. You provide a custom search action. This custom search option, besides of search/filter, also generates a fake option and prepends it to the other, so it's always the first. Since it's a "real" options arrow keys will work.
3. When selecting an option, you check first if that option is the fake one. If so, you create the new entry and select it on the fly.
4. Visual appearance perhaps can be achieved with groups + some css, but if that is not enough, you should be able to roll your own `optionsComponent` with any markup you want. Just use the default one as inspiration.

I haven't tried this pattern but is certainly one I want to enable, so if for some reason the component is not flexible enough, let me know and we'll figure out how to do it.
