### ISSUE TITLE
Result priority?

### ISSUE THREAD

**Issue by mastastealth** [cibernox/ember-power-select#736]
Is there to filter certain results to the top? I was hoping returning higher values would sort them that way but it doesn't, and I couldn't find anything in the docs in regards to this.

**Comment by cibernox** [comment]
Actually I designed the component with that in mind (that is why the matcher function has to return a number and not true/false) but I never finished the implementation.

If you want to give it a spike, you'd just have to improve this function to sort results based on the returned number.

**Comment by mastastealth** [comment]
Could you point me in the right direction/file? 

I would think once the matcher receives the return, there's some in between process that tosses it into `results`. The matcher itself wouldn't/can't do the sorting...could it?

**Comment by cibernox** [comment]
Luckily this logic is pretty contained in a recursive function, so you can fix this without changing a single like of the components. 

The point of change would be exactly this: https://github.com/cibernox/ember-power-select/blob/master/addon/utils/group-utils.js#L90

In here instead of pushing the result, it should be inserted in the right position of the array according with the number.
