### ISSUE TITLE
Arrow should probably not by default be grey

### ISSUE THREAD

**Issue by flyrev** [cibernox/ember-power-select#747]
In all examples on http://www.ember-power-select.com/ the arrow is grey. This looks "disabled". By default the arrow should probably be black.

Do you have a recommended way of styling the arrow for now?

**Comment by cibernox** [comment]
By default the arrow has the same color than the border (#aaa iirc).

If you are using sass, you can change many styles by defining some variables.

By example, to change both the border (and the arrow will default to this color) you can do

```scss
$ember-power-select-border-color: #888;
@import 'ember-power-select;
```

If you want to leave the border color as #aaa and make the arrow darker, you can change the color of the arrow alone:

```scss
$ember-power-select-trigger-icon-color: #888;
@import 'ember-power-select;
```

You have a lot of sass variables to modify the default styles. If you don't use sass you can just override the styles as you want: http://www.ember-power-select.com/docs/styles

I don't plan to change the default theme now, since the addons is already stable (1.0 is comming soon), but it is easy enough to style it your way.

**Comment by flyrev** [comment]
That did not work for me. See example repo at https://github.com/flyrev/ember-power-select-example

**Comment by cibernox** [comment]
@flyrev You need to use sass (install ember-cli-sass), delete `app.css` and fix the syntax error in `app.scss`

**Comment by flyrev** [comment]
Worked like a charm! Thanks! :D
