### ISSUE TITLE
Need allowBlank option

### ISSUE THREAD

**Issue by pohodnya** [cibernox/ember-power-select#757]
I need allowBlank option. When the option value is false in the drop-down list automatically selects the first item and its value is assigned.

**Comment by cibernox** [comment]
Not sure if I follow. You mean that the select should, before opening it interacting with it in any form, select a value?

**Comment by pohodnya** [comment]
@cibernox Yes, once the page is loaded.

**Comment by cibernox** [comment]
That should not be done by the addon but by the user. If you want the first option to be selected by default, a computed property will be enough:

```hbs
{{#power-select options=options selected=selected onchange=(action (mut selected)) ...}}
```

```js
selected: computed.oneWay('options.firstObject')
```

**Comment by pohodnya** [comment]
It's not exactly what I need.
```slim
power-select[
  options=subtypes
  searchEnabled=false
  selected=model.subtype
  onchange=(action (mut model.subtype))
  ] as |subtype|
    = subtype.name
```
**selected** - a field of model, its value can be set and can be not set. If I'm going to use what you have to offer, **selected** will always have a value of the first options element. If I do so in the controller, then it will probably look like this:

```coffeescript
setSelected: Ember.on 'init', ->
  unless @get('model.subtype')? then @set('model.subtype', @get('subtypes.firstObject'))
```

But it is inconvenient for every occasion, especially if the same template several power-select components. Add option in component will be much more convenient. Then add this logic in component.

**Comment by cibernox** [comment]
I understand now. 
But I still think that this is pretty unidiomatic that a component like a select invokes the `onchange` action without user interaction. 

Ember Power Select wants to be a _slightly_ low level component that instead of implementing every possible feature gives tools for users to do it. If you want this feature you can create a component withour markup that wraps Ember Power Select, forwards all received options to the inner component and implements this functionality its `on('init')`.

In fact this is how the [multiple select](https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select-multiple.hbs) in the project is implemented. It's just a wrapper around the basic select that customizes the behaviour.

**Comment by pohodnya** [comment]
Well, I will implement special for yourself. Thanks.
