### ISSUE TITLE
Missing docs about why `searchField` is required in multiple-selects with search & non-string options

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#770]
The reason is that when deleting the last option using the backspace, EPS wants to convert the option into a text and put it in the searchbox, but with objects it cannot do that without a hint.

Perhaps I could soften this warning and just delete the entire word if it's not present.

**Comment by christophersansone** [comment]
A little late feedback here.  Personally, I believe it often makes sense to delete the entire item with a single backspace press.  Oftentimes the items in the list will represent a model.  It's nice to type in a partial name to find it, but once it is selected, it does not necessarily make sense for the backspace key to convert it back to a partial.  Most of the time, I would prefer the backspace key to simply remove the model from the list.

This behavior is pretty common in other apps too.  Both iMessage on iOS and Mail for Mac OS X behave this way when specifying the recipients.

So, I believe it should be configurable.  If `searchField` is specified, the backspace key can convert the item back to a string as it does to day.  If `searchField` is not specified, the backspace key should remove the entire item without error.  There is no need for an error or warning because they are both appropriate behavior... it just needs to be described in the documentation.

**Comment by cibernox** [comment]
If when when the options are objects and there is no `searchField` we delete the items completely without converting them to text, then the behaviour would be different depending on whether or not the options are objects or strings, which I think it's unexpected and ultimately bad. 

However, if you don't want the default behaviour or replacing the last item by it's text representation and you just want to remove it, you can do it in three lines of code:

```hbs
{{#power-select-multiple options=opts selected=choices onchange=(action (mut choices)) onkeydown=(action "handleKeyDown") as |opt|}}
  {{opt}}
{{/power-select-multiple}}
```

```js
    handleKeyDown(select, e) {
      if (e.keyCode === 8 && e.target.value === '' && select.selected.length > 0) {
        select.actions.select(select.selected.slice(0, -1));
        return false;
      }
    }
```

**Comment by christophersansone** [comment]
Thanks @cibernox !  This little trick will work great.  I use this behavior so much that I'll encapsulate it into its own component.

I can understand not wanting different behavior between strings and objects out of the box.  Wondering if there would be a desire for a separate option to toggle this behavior, regardless of what type of item is passed.  In the meantime, I'll just handle `onKeyDown` as you suggest.

Thanks again!
