### ISSUE TITLE
Is this by design?

### ISSUE THREAD

**Issue by denzo** [cibernox/ember-power-select#784]
I found myself trying to customise the `selectedItemComponent` in the `power-select-multiple` and  needed to remove the `X` delete button on each selected item.

Then I found that `selectedItemComponent` is only replacing the content of `<li class="ember-power-select-multiple-option">` element and is inserted after the remove button.

https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select-multiple/trigger.hbs#L12

I wonder if everyone would benefit from the following which would provide further customisation including the look and feel of the remove button.

```
{{#if selectedItemComponent}}
  {{component selectedItemComponent
    tagName="li" class="ember-power-select-multiple-option"
    option=(readonly opt) select=(readonly select)}}
{{else}}
  <li class="ember-power-select-multiple-option">
    {{#unless select.disabled}}
      <span role="button"
        aria-label="remove element"
        class="ember-power-select-multiple-remove-btn"
        data-selected-index={{idx}}>
        &times;
      </span>
    {{/unless}}
    {{yield opt select}}
  </li>
{{/if}}
```

**Comment by cibernox** [comment]
Yeah, that is a tricky one. It was done that way because most of the time people want to customise the content of the selected item but not change the delete button. If I put the delete button inside the selectedItemController everyone wanting to change just the text would have to replicate the template logic of when the x button is displayed. 

The most common thing to do with the x button is moving it to the left, which can be done with css, so I opted to leave it out. 

So yes, it is intentional, but just for a matter of making the most common use case more ergonomic. 

Depending on what you want I can describe a way of achieving it. I've done almost everything you can imagine with the trigger of selects.

**Comment by denzo** [comment]
Ok, I see, it totally makes sense now. I used the `triggerComponent` to achieve the full `selectedItem` customisation.

Thanks for a your quick response. Loving your work!

**Comment by cibernox** [comment]
Yes, that is the way to go 👍
