### ISSUE TITLE
remove ember-truth-helpers from dependencies

### ISSUE THREAD

**Issue by akatov** [cibernox/ember-power-select#810]
is it really necessary to bring them in as a dependency? Would you consider moving them to devDependencies for the dummy app, and I could submit a PR that replaces all usage of truth helpers in the addon with computed properties?

**Comment by cibernox** [comment]
I don't think that a refactor to use computed properties would work because those helpers are usually used from within loops, and you cannot refactor those into computed properties. Example:

```hbs
{{#each model as |foo|}}
  <div class={{if (eq foo selected) '--selected'}}>{{foo}}</div>
{{/each}}
```

Why do you want to remove it? Ember truth helpers is already used in 8 or 9 out of 10 ember apps, so for most of them this dependency adds no extra weight.

**Comment by miguelcobain** [comment]
@cibernox where did those statistics came from? I'm curious. I don't personally use it.

> I don't think that a refactor to use computed properties would work because those helpers are usually used from within loops

The way to do this would be to create an auxiliary computed like:

```js
something: computed('model.[]', 'selected', function() {
  return this.get('model').map((model) => {
    return {
      model,
      isSelected: this.get('selected') === model;
    }
  });
})
```

I think every byte and build second is important when talking about such a widely used addon such as eps. :)

**Comment by cibernox** [comment]
It was an unscientific estimation, based in the projects I've seen. 
In https://emberobserver.com/ it's the most used used addon among the non-official ones (i'd consider ember-cli-sass official-ish).
It's also a runtime dependency of a few very popular addons (even excluding EPS & family). 

Besides, it's just 122 lines of JS.

I'd be happy to remove it if a CP approach proves to be faster tho, but if it's just because of the size seems a bit "bean counting". It probably doesn't worth the effort.

**Comment by akatov** [comment]
@cibernox I agree that using the `eq` helper is the easiest way to use eps, but I don't see why I should be forced to use it if I don't want to. I for one don't like ember-truth-helpers because a) I don't think they're consistent and b) they encourage putting too much logic in the template.
More importantly, I'm not talking about changing the dummy app to use computed properties - I think it's actually a good idea to use the truth helpers there for demonstration purposes, and I don't mind eps having truth helpers as a devDependency. I'm talking about refactoring the components and templates inside `addon` to replace the `(and ... (not ..))` expressions in templates with computed properties inside the components.

**Comment by cibernox** [comment]
Using a computed property in a component will be a bit complicated because what I mentioned. The helper is used from within a loop, but if you find a way go ahead.

Just take into account that you must use `Ember.isEqual`, not just `===`.
