### ISSUE TITLE
`typeInSearch` test helper is not working if you have a power select after multiple one

### ISSUE THREAD

**Issue by mupkoo** [cibernox/ember-power-select#812]
If you have a component that has a multiple select and a select after the multiple one like so

```handlebars
{{ power-select-multiple ...
{{ power-select ...
```

`typeInSearch` always searches in the multiple one.

One way to improve this, is to add `scope` to `typeInSearch`. The other way is to export `typeText` as well, so it can be used as well.

Let me know what do you think, and I will open a PR.

Thank you :)

**Comment by cibernox** [comment]
Yeah, that would be a good addition. I'd prefer the first argument of the function to be the scope and the second to be the text for consistency, but since the scope will be optional you'll have to check for the length of the arguments to consider the text the first or the second argument.

There isn't any test for integration test helper (there is for acceptance tests tho). Could you create a new test in `/tests/integration` to test the test helper?

**Comment by mupkoo** [comment]
Closed by #813
