### ISSUE TITLE
Material Theme - Display Floating Label

### ISSUE THREAD

**Issue by dephora** [cibernox/ember-power-select#814]
Within the Material Theme - would it be possible to allow for an option to leave the floating label displayed upon focus instead of destroying it with a selection?

**Comment by cibernox** [comment]
@dephora Sadly that is not possible just just the CSS theme since it's just a bunch of CSS properties over the default styles. For a more accurate material-design flavour, check https://github.com/miguelcobain/ember-paper.

The select is based on ember-power-select, but the appearance and behaviour is customized much deeper.
