### ISSUE TITLE
Limit the number of result

### ISSUE THREAD

**Issue by Swizz** [cibernox/ember-power-select#930]
Hi there,

I am using the last release of Ember Power Select to allow user to search inside a group list of 360+ group and 15+ items each.
But, I experience sever performance issue. At least 3sec to render.

So, I wanted to limit the number of item in list just the most relevant one according to search.
I digged into matcher/search function and I found a suitable solution.
Nethertheless, at the first select use, the search function is not called because the search input is empty.

So is there a way to call the search function even if the input box is empty ?

Cheers,

**Comment by cibernox** [comment]
Yes, but calling the search will populate the input with the search term. 
My advice is that, since you can combine an initial set of option with a search, to pass that reduced set of options `option=mostLikelyOpts` and let the search be a regular search.

**Comment by Swizz** [comment]
So, there is no way to let search do the search and limit the rendered items to the first 100 ?
I think users will never deep dive into lots of items, they will narrow their search.

**Comment by cibernox** [comment]
There is always a way, at the end you can completely replace every piece of the select with your own components, however there isn't a magical property you can pass that does this. However something I started working in but never got it finished might help be helpful.

My plan was to create a variant of the power select that uses vertical-collection to be able to render tens of thousands of items with no sweat because only those that are visible are rendered for real.
[This](https://github.com/cibernox/ember-power-select-collection) was my spike, I need to continue working on it.

**Comment by Swizz** [comment]
Understood, I will take a look and continue to experiment. Thank you for your answers.

**Comment by cibernox** [comment]
I'm going to close this, but feel free to reopen if you need to
