### ISSUE TITLE
`options` list not cleared while loading

### ISSUE THREAD

**Issue by alexmadjar** [cibernox/ember-power-select#934]
I hooked up ember-power-select `options=myComputedProperty` where my computed property is hooked up to a network request.  While that property is computing, power select knows to use the loading text, but oddly it doesn't clear the previous options, so the UX is:

```
+----------+      +----------+
|loading...|      |  Next1   | 
|  Prev2   |      |  Next2   |
|  Prev3   |  =>  |  Next3   |
|  Prev4   |      |  Next4   |
|  Prev5   |      |  Next5   |
+----------+      +----------+
```

The behavior I would expect is:

```
+----------+      +----------+
|loading...|      |  Next1   | 
+----------+      |  Next2   |
              =>  |  Next3   |
                  |  Next4   |
                  |  Next5   |
                  +----------+
```

**Comment by cibernox** [comment]
Sorry, I've been on holidays all last week.

Actually, this behaviour is intended, not an oversight. Clearing the results of a search while a new search in in progress is not usually what we want, since the flickering of the results is visually annoying. Other selects libraries follow the same approach: https://select2.github.io/examples.html#data-ajax

As anything else in this component, if you **really** want the list of options to dissapear, you can customize [the template of the **options component**](https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/options.hbs) so it doesn't display any option while loading.

**Comment by k-dauda** [comment]
This is a regression from the fix in https://github.com/cibernox/ember-power-select/issues/208
Why not clear the `_resolvedOptions` before the promise resolves on this line https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.ts#L318?
